title: Ayse Irem Karabag
email: airemka@yorku.ca
description: >-
  Doctoral student in English at York University, researching critical refugee
  studies, queer/gender studies, and world literature.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ikarabag
linkedin_username: ayse-irem-karabag-38a937113
orcid: 0000-0000-0000-0000
google_scholar: _yFFf0QAAAAJ
substack_url: iremkarabag.substack.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"

# Collections
collections:
  publications:
    output: true
    permalink: /publications/:title/
  projects:
    output: true
    permalink: /projects/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "publication"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE.md
